### Code was adapted from https://github.com/Capblancq/RDA-landscape-genomics/blob/e2cb3cb5530e286d79875f619314d563938145e3/RDA_landscape_genomics.Rmd
---
title: "Adaptive Indices"
author: "Kirsten Hein"
date: "2023-11-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load Packages and Set-up Environment
```{r}
library(sf)
library(sp)
library(rnaturalearthhires)
library(rnaturalearth)
library(RColorBrewer)
library(ggplot2)
library(viridis)
library(vegan)
library(raster)
library(terra)

setwd("C:/Users/kirst/OneDrive - Colostate/Documents/CSU/McKay_Lab/PhD_doc/Dissertation_Chapters/Chap1_TefPopGen/tef_data/Data_Excel/Outlier Detection/RDA")
load("wolf.rda.RData")
load("C:/Users/kirst/OneDrive - Colostate/Documents/CSU/McKay_Lab/PhD_doc/Dissertation_Chapters/Chap1_TefPopGen/tef_data/Data_Excel/Outlier Detection/RDA/raster_subset_adaptive_values.RData")
```



### Function to project the adaptive component turnover across the landscape
```{r}
adaptive_index <- function(RDA, K, env_pres, range = NULL, method = "loadings", scale_env, center_env){
# Formatting environmental rasters for projection
var_env_proj_pres <- as.data.frame(rasterToPoints(env_pres[[row.names(RDA$CCA$biplot)]]))
# Standardization of the environmental variables
var_env_proj_RDA <- as.data.frame(scale(var_env_proj_pres[,-c(1,2)], center_env[row.names(RDA$CCA$biplot)], scale_env[row.names(RDA$CCA$biplot)]))
# Predicting pixels genetic component based on RDA axes
Proj_pres <- list()
if(method == "loadings"){
for(i in 1:K){
ras_pres <- rasterFromXYZ(data.frame(var_env_proj_pres[,c(1,2)], Z = as.vector(apply(var_env_proj_RDA[,names(RDA$CCA$biplot[,i])], 1, function(x) sum( x * RDA$CCA$biplot[,i])))), crs = crs(env_pres))
names(ras_pres) <- paste0("RDA_pres_", as.character(i))
Proj_pres[[i]] <- ras_pres
names(Proj_pres)[i] <- paste0("RDA", as.character(i))
}
}
# Prediction with RDA model and linear combinations
if(method == "predict"){
pred <- predict(RDA, var_env_proj_RDA[,names(RDA$CCA$biplot[,i])], type = "lc")
for(i in 1:K){
ras_pres <- rasterFromXYZ(data.frame(var_env_proj_pres[,c(1,2)], Z = as.vector(pred[,i])), crs = crs(env_pres))
names(ras_pres) <- paste0("RDA_pres_", as.character(i))
Proj_pres[[i]] <- ras_pres
names(Proj_pres)[i] <- paste0("RDA", as.character(i))
}
}
# Mask with the range if supplied
if(!is.null(range)){
Proj_pres <- lapply(Proj_pres, function(x) mask(x, range))
}
# Returning projections for current climates for each RDA axis
return(Proj_pres = Proj_pres)
}
```


### Scale and Center Select Environmental Variables
```{r}
pred <- read.csv(env_subset_rda.csv")
pred <- pred[-1]
Env <- scale(pred, center = TRUE, scale = TRUE)
scale_env <- attr(Env, 'scaled:scale')
center_env <- attr(Env, 'scaled:center')
```


### Create "env_pres" raster file
```{r}
r <- getData("worldclim", var="bio",res=10)
et <- ne_states(country = "ethiopia", returnclass = "sf")
geometry <- et$geometry
sp_geometry <- as(geometry, "Spatial")
raster_subset <- raster::mask(r, mask = sp_geometry)
```
